"use client";

import { ArrowDown, Inbox } from "lucide-react";
import { useState } from "react";
import type { LeadRow } from "../../types/lead";
import LeadDetails from "./LeadDetails";

export default function LeadsTable({ leads, onChanged = () => window.location.reload() }: { leads: LeadRow[]; onChanged?: () => void }) {
  const [selected, setSelected] = useState<LeadRow | null>(null);
  if (!leads.length) return <div className="flex min-h-64 flex-col items-center justify-center rounded-2xl border border-dashed border-white/10 bg-[#111413] px-6 text-center"><Inbox className="h-7 w-7 text-zinc-600" /><h3 className="mt-4 text-sm font-semibold text-white">No leads match these filters</h3><p className="mt-2 text-xs text-zinc-600">New qualified leads will appear here automatically after they are captured.</p></div>;
  return <><div className="overflow-hidden rounded-2xl border border-white/10 bg-[#111413]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-4 sm:px-5"><div><h2 className="text-sm font-semibold text-white">All leads</h2><p className="mt-1 text-xs text-zinc-600">{leads.length} matching {leads.length === 1 ? "lead" : "leads"}</p></div><span className="inline-flex items-center gap-1 text-[10px] uppercase tracking-[0.12em] text-zinc-600">Newest <ArrowDown className="h-3 w-3" /></span></div><div className="overflow-x-auto"><table className="w-full min-w-225 text-left text-xs"><thead className="border-b border-white/10 text-[10px] uppercase tracking-[0.12em] text-zinc-600"><tr>{["Name", "Email", "Service", "Score", "Intent", "Action", "Status", "Created at"].map((heading) => <th className="px-4 py-3 font-medium sm:px-5" key={heading}>{heading}</th>)}</tr></thead><tbody>{leads.map((lead) => <tr className="cursor-pointer border-b border-white/6 text-zinc-400 transition hover:bg-white/3 last:border-0" key={lead.id} onClick={() => setSelected(lead)}><td className="px-4 py-4 font-medium text-white sm:px-5">{lead.name}</td><td className="px-4 py-4 sm:px-5">{lead.email}</td><td className="px-4 py-4 sm:px-5">{lead.service}</td><td className="px-4 py-4 font-semibold text-lime-300 sm:px-5">{lead.score}/100</td><td className="px-4 py-4 sm:px-5">{lead.intent || "Unknown"}</td><td className="max-w-48 truncate px-4 py-4 text-zinc-500 sm:px-5">{lead.recommended_action || "-"}</td><td className="px-4 py-4 sm:px-5"><span className={`rounded-full px-2 py-1 text-[10px] ${lead.status === "Hot Lead" ? "bg-lime-300/10 text-lime-300" : lead.status === "Warm Lead" ? "bg-yellow-300/10 text-yellow-300" : "bg-white/10 text-zinc-500"}`}>{lead.status.replace(" Lead", "")}</span></td><td className="whitespace-nowrap px-4 py-4 sm:px-5">{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(lead.created_at))}</td></tr>)}</tbody></table></div></div>{selected && <LeadDetails lead={selected} onClose={() => setSelected(null)} onRegenerated={() => { setSelected(null); onChanged(); }} />}</>;
}
