"use client";

import { RefreshCw, X } from "lucide-react";
import { useState } from "react";
import type { LeadRow } from "../../types/lead";

export default function LeadDetails({ lead, onClose, onRegenerated }: { lead: LeadRow; onClose: () => void; onRegenerated: () => void }) {
  const [working, setWorking] = useState(false);
  const [message, setMessage] = useState("");
  async function regenerate() { setWorking(true); setMessage(""); const response = await fetch(`/api/admin/leads/${lead.id}/intelligence`, { method: "POST" }); setMessage(response.ok ? "Insight regenerated." : "Unable to regenerate insight. Run the intelligence SQL if needed."); setWorking(false); if (response.ok) onRegenerated(); }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-label="Lead details"><div className="max-h-[90dvh] w-full max-w-xl overflow-y-auto rounded-t-3xl border border-white/10 bg-[#111413] p-5 shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[0.18em] text-lime-300">Lead intelligence</p><h2 className="mt-2 text-2xl font-semibold text-white">{lead.name}</h2><p className="mt-1 text-sm text-zinc-500">{lead.email}</p></div><button aria-label="Close details" className="rounded-full p-2 text-zinc-500 hover:bg-white/10 hover:text-white" onClick={onClose} type="button"><X className="h-5 w-5" /></button></div><div className="mt-6 grid grid-cols-2 gap-3 text-xs sm:grid-cols-3">{[["Service", lead.service], ["Budget", lead.budget], ["Timeline", lead.timeline], ["Score", `${lead.score}/100`], ["Status", lead.status], ["Intent", lead.intent || "Unknown"]].map(([label, value]) => <div className="rounded-xl border border-white/10 bg-white/3 p-3" key={label}><p className="text-zinc-600">{label}</p><p className="mt-1 text-zinc-200">{value}</p></div>)}</div><div className="mt-4 space-y-3"><div className="rounded-xl border border-white/10 bg-white/3 p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-zinc-600">Conversation summary</p><p className="mt-2 text-sm leading-6 text-zinc-300">{lead.conversation_summary || "No summary has been generated yet."}</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-white/3 p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-zinc-600">Recommended action</p><p className="mt-2 text-sm text-zinc-300">{lead.recommended_action || "No action yet."}</p></div><div className="rounded-xl border border-white/10 bg-white/3 p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-zinc-600">Confidence</p><p className="mt-2 text-2xl font-semibold text-lime-300">{lead.intelligence_confidence ?? "-"}<span className="text-xs font-normal text-zinc-600">/100</span></p></div></div>{lead.lost_reason && <div className="rounded-xl border border-yellow-300/20 bg-yellow-300/6 p-4"><p className="text-[10px] uppercase tracking-[0.14em] text-yellow-300">Lost reason</p><p className="mt-2 text-sm text-zinc-300">{lead.lost_reason}</p></div>}</div><div className="mt-6 flex items-center justify-between gap-3 border-t border-white/10 pt-4"><p className="text-xs text-lime-300">{message}</p><button className="inline-flex items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 text-xs font-medium text-zinc-300 hover:border-lime-300/50 hover:text-white disabled:opacity-50" disabled={working} onClick={() => void regenerate()} type="button"><RefreshCw className={`h-3.5 w-3.5 ${working ? "animate-spin" : ""}`} />{working ? "Regenerating..." : "Regenerate Insight"}</button></div></div></div>;
}
